In [1]:
# This piece of code was is to analyse the datafile for each folder

In [2]:
import os
import pandas as pd

dir_path = r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset"

all_data = []

for root, dirs, files in os.walk(dir_path):

    # Get current folder name
    folder_name = os.path.basename(root)

    for file in files:

        if file.endswith('.txt'):

            file_path = os.path.join(root, file)

            print(file_path)

            df = pd.read_csv(
                file_path,
                delimiter=',',
                header=None,
                names=['Full Energy', 'Variance']
            )

            # Add folder name as a column
            df['Protein_name'] = folder_name

            all_data.append(df)

# Combine all dataframes
final_df = pd.concat(all_data, ignore_index=True)

print(final_df.head())

C:\Users\carlo\Downloads\AI\AI\dataset\dataset\16pk_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1a62_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ab1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1af7_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ah7_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ail_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1aol_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b0n_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b25_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_F\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b8d_K\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bgf_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bkp_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bq8_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1btk_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bx7_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1by2_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c1k_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c52_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c96_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1chd_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cm3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1coj_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cpq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ctf_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cuo_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cvr_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d2t_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d4t_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dci_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dfu_P\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dj0_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dk8_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dlj_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1doi_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dow_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dpt_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dtd_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dvo_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dwk_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dzf_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e6y_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e7l_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ear_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1eb0_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1enj_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1esw_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ewf_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ez3_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f20_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_G\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f5n_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f9p_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fcz_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fd3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1feh_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fk5_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fm4_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fqi_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fx4_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fxo_G\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g2r_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g6g_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7s_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7t_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g81_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g9g_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gnt_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gpj_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqe_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqv_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gte_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gwe_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h02_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h16_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h17_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h2e_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h8e_G\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h99_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hbn_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hc9_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hoe_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hp1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hq0_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1huf_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hw1_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hye_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i0v_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i2t_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i4m_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ifg_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig0_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijt_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijx_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikp_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikt_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1im5_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1io1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iom_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iqq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iuq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ix9_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j09_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j0p_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j2l_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j5u_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j77_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8e_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8r_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jhs_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jif_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jke_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jmx_G\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jnr_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jo0_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jq5_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1juv_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jwq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_F\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k30_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k5n_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k7c_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k7j_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k8k_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ka1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kew_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kgq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1knt_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1koe_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kop_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kp3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kpt_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1krn_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l2p_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l2w_I\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l2w_J\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l5o_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l9l_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lc3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lfp_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lj5_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1llf_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lln_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lr0_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lri_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ls1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lsl_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lwb_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lwd_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m15_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m5q_I\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m5q_Z\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m7v_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m8s_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m9z_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1md6_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mix_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mjf_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mk0_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mlw_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1msc_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1msk_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mv8_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n2m_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n7z_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n7z_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n8o_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n8u_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n8v_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nf8_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ng6_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nh2_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nij_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1njh_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nkp_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nl1_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nnh_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nns_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ntv_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nty_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o0s_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o1x_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o4k_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o75_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o98_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1oao_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ocy_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1oh9_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ois_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ojh_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ojh_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ojq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ok0_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ouw_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1p27_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1p5g_X\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pby_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pcf_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pch_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pdo_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pp0_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ptq_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1puc_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pv5_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q0q_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q2h_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q74_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q7e_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q8f_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qau_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qb7_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qcs_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qdd_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qgi_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qhv_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ql0_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qlm_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qnx_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qw2_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qwz_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qxo_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qxo_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qxy_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qz4_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r0k_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r5l_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r6l_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r6w_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r8m_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r9f_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rgz_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rk8_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rl6_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rlk_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rm6_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rpo_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rqj_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rrm_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rss_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ru4_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ryl_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1s2o_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1s9r_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1s9u_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sdi_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sei_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sei_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sf9_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1skz_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ssq_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1svb_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sx3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sx3_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t61_E\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t7v_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t8h_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t8k_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t95_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t9i_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tag_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tdz_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tez_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tg7_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tgr_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1thm_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tov_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tt8_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tuk_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tzv_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tzw_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u07_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u09_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u55_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u6r_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u6t_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u7k_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u84_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u8v_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ugp_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ugp_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uha_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uoy_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1upt_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1upt_D\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1usm_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1utg_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uwk_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ux6_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uxy_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uz3_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uz3_B\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1uzp_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v0w_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v1h_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v2z_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v30_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v4p_C\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v7r_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v7z_F\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1v9m_A\C_V.txt
C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1vaj_A\C_V.txt

In [3]:
final_df

        Full Energy    Variance Protein_name
0     448432.420602  599.266926       16pk_A
1     229293.069415  306.417972       1a62_A
2      29975.425891   40.057945       1ab1_A
3     267632.549965  357.653301       1af7_A
4     263946.537107  352.727462       1ah7_A
...             ...         ...          ...
1933  445033.132245  594.724254       8cxl_A
1934  584998.356340  781.768111       8dkp_A
1935  424533.020281  567.328735       8dkp_B
1936  453535.001060  606.085807       8ezh_B
1937  325060.399489  434.397553       8htw_B

[1938 rows x 3 columns]

In [4]:
final_df['Variance']>500

0        True
1       False
2       False
3       False
4       False
        ...
1933     True
1934     True
1935     True
1936     True
1937    False
Name: Variance, Length: 1938, dtype: bool

In [5]:
#Filtering the dataframe to see what has the highest variance.

filtered_df_top= final_df[final_df['Variance'] > 3000]


print(filtered_df_top)

       Full Energy     Variance Protein_name
308   2.405386e+06  3214.460048       1ux6_A
1664  3.617074e+06  4833.710592       5vz0_A
1827  2.632784e+06  3518.345736       6sup_A

In [6]:
filtered_df_bottom = final_df[final_df['Variance'] < 50]
print(filtered_df_bottom)


#1ab1 has 1 ligand interaction
#4gjp_A has 0 ligand interactions
#1dtd_B has 2 ligand interactions and 1 ion interaction

# Chain interactions have no effect from this

#Ligand interactions are a contributor to the full energy and variance.
#Ion interactions too are a main  contributor.
# Filtering may have removed the values


#Scale it with the atom size.

       Full Energy   Variance Protein_name
2     29975.425891  40.057945       1ab1_A
44    34988.239845  46.756867       1dtd_B
66    26267.376840  35.102659       1fd3_A
491   24126.467252  32.241634       2erl_A
1200  31435.788760  42.009515       3u7t_A
1312      0.000000   0.000000       4gjp_A
1734  27341.129330  36.537578       6e6o_A

# This will be done

From using code we can see that the three highest variances are 5vz0_A

**RMSD the top 3 with the Variance**

![alt.text](1u6xa.png)
*1u6xa*
![alt.text](5vz0_A.png)
*5vz0_A*
![alt.text](6supA.png)
*6supA*

** This is the generalised of each **

![alt.text](1u6xaprop.png)
*1u6xa*
![alt.text](5vz0_A.Prop.png)
*5vz0A*
![alt.text](6supAProp.png)
*6SupA*

They all have an Alpha Helix at 109,162,255

In [7]:
print(filtered_df_bottom)

       Full Energy   Variance Protein_name
2     29975.425891  40.057945       1ab1_A
44    34988.239845  46.756867       1dtd_B
66    26267.376840  35.102659       1fd3_A
491   24126.467252  32.241634       2erl_A
1200  31435.788760  42.009515       3u7t_A
1312      0.000000   0.000000       4gjp_A
1734  27341.129330  36.537578       6e6o_A

4gjp_A - This a value of 0, I Will explore what this looks like on the graph.

**It has no ion interactions which is why it generates no energy which makes sense.**

![alt.text](4gjp_A.png)
Normal graph
![alt.text](4gjp_A_prop.png)
Properties graph

we can remove it from the dataset as it does not have any effect.

In [8]:
final_df[final_df['Protein_name'] == '4gjp_A'] #So i have to look into what has done this one.

      Full Energy  Variance Protein_name
1312          0.0       0.0       4gjp_A

In [9]:
final_df = final_df[final_df['Protein_name'] != '4gjp_A']

In [10]:
final_df

        Full Energy    Variance Protein_name
0     448432.420602  599.266926       16pk_A
1     229293.069415  306.417972       1a62_A
2      29975.425891   40.057945       1ab1_A
3     267632.549965  357.653301       1af7_A
4     263946.537107  352.727462       1ah7_A
...             ...         ...          ...
1933  445033.132245  594.724254       8cxl_A
1934  584998.356340  781.768111       8dkp_A
1935  424533.020281  567.328735       8dkp_B
1936  453535.001060  606.085807       8ezh_B
1937  325060.399489  434.397553       8htw_B

[1937 rows x 3 columns]

In [11]:
# I removed it

In [12]:
final_df

        Full Energy    Variance Protein_name
0     448432.420602  599.266926       16pk_A
1     229293.069415  306.417972       1a62_A
2      29975.425891   40.057945       1ab1_A
3     267632.549965  357.653301       1af7_A
4     263946.537107  352.727462       1ah7_A
...             ...         ...          ...
1933  445033.132245  594.724254       8cxl_A
1934  584998.356340  781.768111       8dkp_A
1935  424533.020281  567.328735       8dkp_B
1936  453535.001060  606.085807       8ezh_B
1937  325060.399489  434.397553       8htw_B

[1937 rows x 3 columns]

In [13]:
template = pd.DataFrame(columns=['NodeId1','Interaction','NodeId2','Distance','Angle','Atom1','Atom2','Donor','Postive','Cation'])

In [14]:
template

Empty DataFrame
Columns: [NodeId1, Interaction, NodeId2, Distance, Angle, Atom1, Atom2, Donor, Postive, Cation]
Index: []

In [15]:
path = r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1af7_A\1af7_A.rout"

with open(path, "r", encoding="utf-8", errors="replace") as f:
    lines = f.readlines()

headers = lines[6].rstrip("\n").split("\t")

rows = []
for line in lines[7:]:
    line = line.rstrip("\n")
    if not line.strip():
        continue

    parts = line.split("\t")

    # Make row length match header length
    if len(parts) < len(headers):
        parts += [""] * (len(headers) - len(parts))
    elif len(parts) > len(headers):
        parts = parts[:len(headers)]

    rows.append(parts)

df = pd.DataFrame(rows, columns=headers)

print(df.head())
df.to_csv("parsed_rout.csv", index=False)

      NodeId1  Interaction     NodeId2 Distance    Angle Atom1 Atom2  \
0  _:10:_:LEU  HBOND:MC_SC  _:41:_:TYR    2.610  168.198     O    OH
1  _:10:_:LEU    VDW:SC_SC  _:45:_:VAL    2.903      nan   HB1   CG1
2  _:10:_:LEU    VDW:SC_MC  _:54:_:ASP    2.884      nan  HD23    CA
3  _:10:_:LEU    VDW:SC_MC  _:54:_:ASP    3.369      nan   CD2     C
4  _:10:_:LEU    VDW:SC_SC  _:56:_:PHE    2.419      nan   HB2   HE2

        Donor Positive Cation Orientation Model
0  _:41:_:TYR                                 1
1                                             1
2                                             1
3                                             1
4                                             1

In [16]:
df = df.iloc[:496]

In [17]:
df['Cation'].unique()

array(['', '_:37:_:ARG', '_:27:_:ARG'], dtype=object)

In [18]:
data_frame = pd.read_csv('parsed_rout.csv')

In [19]:
data_frame

,NodeId1,Interaction,NodeId2,Distance,Angle,Atom1,Atom2,Donor,Positive,Cation,Orientation,Model
0,_:10:_:LEU,HBOND:MC_SC,_:41:_:TYR,2.610,168.198,O,OH,_:41:_:TYR,NaN,NaN,NaN,1
1,_:10:_:LEU,VDW:SC_SC,_:45:_:VAL,2.903,NaN,HB1,CG1,NaN,NaN,NaN,NaN,1
2,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,2.884,NaN,HD23,CA,NaN,NaN,NaN,NaN,1
3,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,3.369,NaN,CD2,C,NaN,NaN,NaN,NaN,1
4,_:10:_:LEU,VDW:SC_SC,_:56:_:PHE,2.419,NaN,HB2,HE2,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
767,_:271:_:TYR,_,271,TYR,RES,E,10,0.000,25.720,21.900,29.590,1af7_A.pdb#271._
768,_:272:_:ALA,_,272,ALA,RES,E,3,0.000,24.690,24.720,27.190,1af7_A.pdb#272._
769,_:273:_:LEU,_,273,LEU,RES,E,2,0.000,21.540,26.790,26.940,1af7_A.pdb#273._
770,_:274:_:SER,_,274,SER,RES,,2,0.000,18.200,24.960,26.520,1af7_A.pdb#274._
771,RING finished successfully,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df[df["Interaction"] == "PIPISTACK:SC_SC"]

,NodeId1,Interaction,NodeId2,Distance,Angle,Atom1,Atom2,Donor,Positive,Cation,Orientation,Model
18,_:16:_:HIS,PIPISTACK:SC_SC,_:56:_:PHE,6.234,34.112,"31.824,26.142,72.438","37.357,25.388,69.665",,,,"I,Θ 56.56,γ 34.11,δ 32.39",1
71,_:41:_:TYR,PIPISTACK:SC_SC,_:56:_:PHE,6.191,37.946,"40.660,20.168,69.257","37.357,25.388,69.665",,,,"I,Θ 20.73,γ 37.95,δ 6.21",1
135,_:72:_:TRP,PIPISTACK:SC_SC,_:75:_:PHE,5.476,79.023,"31.150,34.792,59.900","33.810,30.012,60.153",,,,"T,Θ 45.05,γ 79.02,δ 54.26",1
169,_:86:_:PHE,PIPISTACK:SC_SC,_:158:_:TYR,5.337,87.139,"48.913,21.350,37.178","50.905,25.108,40.402",,,,"T,Θ 10.64,γ 87.14,δ 76.30",1
173,_:86:_:PHE,PIPISTACK:SC_SC,_:175:_:PHE,6.459,74.599,"48.913,21.350,37.178","53.947,23.913,34.047",,,,"T,Θ 51.92,γ 74.60,δ 18.50",1
174,_:87:_:PHE,PIPISTACK:SC_SC,_:93:_:PHE,5.276,63.976,"45.792,19.277,31.088","40.647,20.430,30.907",,,,"T,Θ 38.79,γ 63.98,δ 74.45",1
186,_:92:_:HIS,PIPISTACK:SC_SC,_:218:_:PHE,6.229,72.606,"34.212,18.302,32.004","36.008,24.265,32.132",,,,"T,Θ 39.17,γ 72.61,δ 33.06",1
189,_:92:_:HIS,PIPISTACK:SC_SC,_:249:_:PHE,5.311,69.082,"34.212,18.302,32.004","33.180,22.892,29.538",,,,"T,Θ 69.45,γ 69.08,δ 4.13",1
194,_:93:_:PHE,PIPISTACK:SC_SC,_:218:_:PHE,6.142,16.438,"40.647,20.430,30.907","36.008,24.265,32.132",,,,"P,Θ 44.96,γ 16.44,δ 28.76",1
215,_:99:_:HIS,PIPISTACK:SC_SC,_:107:_:TYR,5.975,69.459,"31.658,26.868,22.816","36.668,29.927,23.932",,,,"T,Θ 44.10,γ 69.46,δ 5.07",1
236,_:110:_:TRP,PIPISTACK:SC_SC,_:141:_:PHE,5.672,62.037,"33.954,32.848,37.070","37.548,37.228,36.813",,,,"T,Θ 56.65,γ 62.04,δ 4.13",1
238,_:110:_:TRP,PIPISTACK:SC_SC,_:208:_:TYR,5.998,62.719,"31.847,33.127,37.357","27.782,34.743,41.460",,,,"T,Θ 5.69,γ 62.72,δ 45.79",1
240,_:110:_:TRP,PIPISTACK:SC_SC,_:214:_:PHE,5.112,39.382,"33.954,32.848,37.070","32.925,35.052,32.573",,,,"I,Θ 32.87,γ 39.38,δ 57.31",1
241,_:110:_:TRP,PIPISTACK:SC_SC,_:214:_:PHE,5.268,38.329,"31.847,33.127,37.357","32.925,35.052,32.573",,,,"I,Θ 31.34,γ 38.33,δ 38.96",1
245,_:110:_:TRP,PIPISTACK:SC_SC,_:238:_:PHE,5.692,86.644,"31.847,33.127,37.357","27.523,29.437,37.657",,,,"T,Θ 20.28,γ 86.64,δ 45.35",1
271,_:121:_:TYR,PIPISTACK:SC_SC,_:158:_:TYR,6.320,78.715,"48.078,29.147,36.447","50.905,25.108,40.402",,,,"T,Θ 40.26,γ 78.71,δ 10.63",1
273,_:121:_:TYR,PIPISTACK:SC_SC,_:198:_:PHE,5.703,68.737,"48.078,29.147,36.447","44.493,32.497,39.353",,,,"T,Θ 59.33,γ 68.74,δ 6.16",1
298,_:138:_:TRP,PIPISTACK:SC_SC,_:195:_:TYR,4.666,22.418,"44.620,31.740,26.535","47.642,35.293,26.652",,,,"P,Θ 76.11,γ 22.42,δ 53.88",1
299,_:138:_:TRP,PIPISTACK:SC_SC,_:195:_:TYR,5.113,20.242,"44.058,32.294,24.578","47.642,35.293,26.652",,,,"P,Θ 59.13,γ 20.24,δ 55.18",1
412,_:218:_:PHE,PIPISTACK:SC_SC,_:249:_:PHE,4.076,7.831,"36.008,24.265,32.132","33.180,22.892,29.538",,,,"P,Θ 62.39,γ 7.83,δ 55.22",1
482,_:256:_:PHE,PIPISTACK:SC_SC,_:271:_:TYR,5.350,24.604,"26.163,22.273,37.163","24.880,19.772,32.612",,,,"P,Θ 38.94,γ 24.60,δ 52.35",1

In [21]:
df[['Shape','Theta','Gamma','Delta']] = df['Orientation'].str.split(',', expand=True)

In [22]:
df.replace()

C:\Users\carlo\AppData\Local\Temp\ipykernel_12228\822458357.py:1: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df.replace()

,NodeId1,Interaction,NodeId2,Distance,Angle,Atom1,Atom2,Donor,Positive,Cation,Orientation,Model,Shape,Theta,Gamma,Delta
0,_:10:_:LEU,HBOND:MC_SC,_:41:_:TYR,2.610,168.198,O,OH,_:41:_:TYR,,,,1,,None,None,None
1,_:10:_:LEU,VDW:SC_SC,_:45:_:VAL,2.903,nan,HB1,CG1,,,,,1,,None,None,None
2,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,2.884,nan,HD23,CA,,,,,1,,None,None,None
3,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,3.369,nan,CD2,C,,,,,1,,None,None,None
4,_:10:_:LEU,VDW:SC_SC,_:56:_:PHE,2.419,nan,HB2,HE2,,,,,1,,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,_:264:_:SER,HBOND:MC_MC,_:272:_:ALA,3.419,155.078,O,N,_:272:_:ALA,,,,1,,Θ 38.94,γ 24.60,δ 52.35
492,_:266:_:ARG,HBOND:MC_MC,_:270:_:VAL,2.794,154.346,N,O,_:266:_:ARG,,,,1,,Θ 38.94,γ 24.60,δ 52.35
493,_:266:_:ARG,VDW:SC_MC,_:270:_:VAL,2.922,nan,HN,C,,,,,1,,Θ 38.94,γ 24.60,δ 52.35
494,_:267:_:GLY,HBOND:MC_MC,_:270:_:VAL,3.483,171.967,O,N,_:270:_:VAL,,,,1,,Θ 38.94,γ 24.60,δ 52.35
495,_:267:_:GLY,VDW:SC_MC,_:270:_:VAL,2.723,nan,HN,O,,,,,1,,Θ 38.94,γ 24.60,δ 52.35

In [23]:
df['Orientation'].unique()

array(['', 'I,Θ 56.56,γ 34.11,δ 32.39', 'S,α 33.10,γ 25.43',
       'S,α 25.33,γ 14.98', 'I,Θ 20.73,γ 37.95,δ 6.21',
       'T,Θ 45.05,γ 79.02,δ 54.26', 'T,Θ 10.64,γ 87.14,δ 76.30',
       'T,Θ 51.92,γ 74.60,δ 18.50', 'T,Θ 38.79,γ 63.98,δ 74.45',
       'T,Θ 39.17,γ 72.61,δ 33.06', 'T,Θ 69.45,γ 69.08,δ 4.13',
       'P,Θ 44.96,γ 16.44,δ 28.76', 'T,Θ 44.10,γ 69.46,δ 5.07',
       'T,Θ 56.65,γ 62.04,δ 4.13', 'T,Θ 5.69,γ 62.72,δ 45.79',
       'I,Θ 32.87,γ 39.38,δ 57.31', 'I,Θ 31.34,γ 38.33,δ 38.96',
       'T,Θ 20.28,γ 86.64,δ 45.35', 'T,Θ 40.26,γ 78.71,δ 10.63',
       'T,Θ 59.33,γ 68.74,δ 6.16', 'P,Θ 76.11,γ 22.42,δ 53.88',
       'P,Θ 59.13,γ 20.24,δ 55.18', 'P,Θ 62.39,γ 7.83,δ 55.22',
       'P,Θ 38.94,γ 24.60,δ 52.35'], dtype=object)

In [24]:
df['Angle']

0      168.198
1          nan
2          nan
3          nan
4          nan
        ...
491    155.078
492    154.346
493        nan
494    171.967
495        nan
Name: Angle, Length: 496, dtype: object

In [25]:
df['Angle'] = df['Angle'].fillna(1)

In [26]:
df['Angle'] = df['Angle'].replace('nan',0)

In [27]:
df['Angle']

0      168.198
1            0
2            0
3            0
4            0
        ...
491    155.078
492    154.346
493          0
494    171.967
495          0
Name: Angle, Length: 496, dtype: object

In [28]:
df.columns

Index(['NodeId1', 'Interaction', 'NodeId2', 'Distance', 'Angle', 'Atom1',
       'Atom2', 'Donor', 'Positive', 'Cation', 'Orientation', 'Model', 'Shape',
       'Theta', 'Gamma', 'Delta'],
      dtype='object')

In [29]:
df

,NodeId1,Interaction,NodeId2,Distance,Angle,Atom1,Atom2,Donor,Positive,Cation,Orientation,Model,Shape,Theta,Gamma,Delta
0,_:10:_:LEU,HBOND:MC_SC,_:41:_:TYR,2.610,168.198,O,OH,_:41:_:TYR,,,,1,,None,None,None
1,_:10:_:LEU,VDW:SC_SC,_:45:_:VAL,2.903,0,HB1,CG1,,,,,1,,None,None,None
2,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,2.884,0,HD23,CA,,,,,1,,None,None,None
3,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,3.369,0,CD2,C,,,,,1,,None,None,None
4,_:10:_:LEU,VDW:SC_SC,_:56:_:PHE,2.419,0,HB2,HE2,,,,,1,,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,_:264:_:SER,HBOND:MC_MC,_:272:_:ALA,3.419,155.078,O,N,_:272:_:ALA,,,,1,,None,None,None
492,_:266:_:ARG,HBOND:MC_MC,_:270:_:VAL,2.794,154.346,N,O,_:266:_:ARG,,,,1,,None,None,None
493,_:266:_:ARG,VDW:SC_MC,_:270:_:VAL,2.922,0,HN,C,,,,,1,,None,None,None
494,_:267:_:GLY,HBOND:MC_MC,_:270:_:VAL,3.483,171.967,O,N,_:270:_:VAL,,,,1,,None,None,None
495,_:267:_:GLY,VDW:SC_MC,_:270:_:VAL,2.723,0,HN,O,,,,,1,,None,None,None

In [30]:
df['Donor'].unique()

array(['_:41:_:TYR', '', '_:16:_:HIS', '_:13:_:SER', '_:17:_:PHE',
       '_:18:_:ARG', '_:37:_:ARG', '_:19:_:ARG', '_:20:_:ILE',
       '_:21:_:CYS', '_:22:_:GLN', '_:23:_:LEU', '_:24:_:ILE',
       '_:25:_:TYR', '_:26:_:GLN', '_:27:_:ARG', '_:28:_:ALA',
       '_:29:_:GLY', '_:202:_:ASN', '_:31:_:VAL', '_:36:_:LYS',
       '_:40:_:VAL', '_:42:_:ASN', '_:43:_:ARG', '_:44:_:LEU',
       '_:45:_:VAL', '_:47:_:ARG', '_:48:_:LEU', '_:49:_:ARG',
       '_:50:_:ALA', '_:51:_:LEU', '_:53:_:LEU', '_:52:_:GLY',
       '_:59:_:TYR', '_:60:_:LEU', '_:61:_:SER', '_:62:_:MET',
       '_:63:_:LEU', '_:64:_:GLU', '_:65:_:ALA', '_:66:_:ASN',
       '_:72:_:TRP', '_:67:_:GLN', '_:69:_:SER', '_:75:_:PHE',
       '_:76:_:ILE', '_:77:_:ASN', '_:147:_:THR', '_:78:_:ALA',
       '_:79:_:LEU', '_:80:_:THR', '_:115:_:SER', '_:82:_:ASN',
       '_:88:_:ARG', '_:165:_:THR', '_:87:_:PHE', '_:220:_:ARG',
       '_:92:_:HIS', '_:221:_:ASN', '_:252:_:HIS', '_:96:_:LEU',
       '_:97:_:ALA', '_:98:_:GLU', '_:99:_:HIS', '_:100:_:ALA',
       '_:107:_:TYR', '_:101:_:ARG', '_:102:_:ARG', '_:103:_:ARG',
       '_:137:_:ARG', '_:139:_:LYS', '_:108:_:ARG', '_:216:_:ALA',
       '_:109:_:VAL', '_:141:_:PHE', '_:110:_:TRP', '_:218:_:PHE',
       '_:111:_:SER', '_:143:_:SER', '_:112:_:ALA', '_:117:_:GLY',
       '_:114:_:ALA', '_:158:_:TYR', '_:121:_:TYR', '_:122:_:SER',
       '_:123:_:ILE', '_:124:_:ALA', '_:125:_:ILE', '_:126:_:THR',
       '_:127:_:LEU', '_:128:_:ALA', '_:129:_:ASP', '_:130:_:ALA',
       '_:131:_:LEU', '_:174:_:TYR', '_:138:_:TRP', '_:140:_:VAL',
       '_:142:_:ALA', '_:199:_:SER', '_:201:_:VAL', '_:149:_:VAL',
       '_:150:_:LEU', '_:151:_:GLU', '_:152:_:LYS', '_:153:_:ALA',
       '_:154:_:ARG', '_:155:_:SER', '_:156:_:GLY', '_:188:_:VAL',
       '_:186:_:VAL', '_:159:_:ARG', '_:162:_:GLU', '_:163:_:LEU',
       '_:160:_:LEU', '_:166:_:LEU', '_:170:_:GLN', '_:171:_:LEU',
       '_:172:_:GLN', '_:173:_:ARG', '_:189:_:ARG', '_:176:_:MET',
       '_:187:_:ARG', '_:178:_:GLY', '_:182:_:HIS', '_:183:_:GLU',
       '_:185:_:LEU', '_:192:_:LEU', '_:193:_:ALA', '_:194:_:ASN',
       '_:190:_:GLN', '_:195:_:TYR', '_:205:_:GLU', '_:208:_:TYR',
       '_:237:_:ARG', '_:214:_:PHE', '_:243:_:LYS', '_:247:_:LEU',
       '_:217:_:ILE', '_:249:_:PHE', '_:219:_:CYS', '_:225:_:TYR',
       '_:222:_:VAL', '_:223:_:MET', '_:224:_:ILE', '_:230:_:THR',
       '_:231:_:GLN', '_:232:_:GLU', '_:233:_:ASP', '_:234:_:ILE',
       '_:235:_:LEU', '_:236:_:ARG', '_:238:_:PHE', '_:241:_:LEU',
       '_:246:_:GLY', '_:248:_:LEU', '_:271:_:TYR', '_:269:_:THR',
       '_:250:_:ALA', '_:251:_:GLY', '_:258:_:ASN', '_:274:_:SER',
       '_:264:_:SER', '_:272:_:ALA', '_:266:_:ARG', '_:270:_:VAL'],
      dtype=object)

In [31]:
df = df.replace({None: 0})

In [32]:
df

,NodeId1,Interaction,NodeId2,Distance,Angle,Atom1,Atom2,Donor,Positive,Cation,Orientation,Model,Shape,Theta,Gamma,Delta
0,_:10:_:LEU,HBOND:MC_SC,_:41:_:TYR,2.610,168.198,O,OH,_:41:_:TYR,,,,1,,0,0,0
1,_:10:_:LEU,VDW:SC_SC,_:45:_:VAL,2.903,0,HB1,CG1,,,,,1,,0,0,0
2,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,2.884,0,HD23,CA,,,,,1,,0,0,0
3,_:10:_:LEU,VDW:SC_MC,_:54:_:ASP,3.369,0,CD2,C,,,,,1,,0,0,0
4,_:10:_:LEU,VDW:SC_SC,_:56:_:PHE,2.419,0,HB2,HE2,,,,,1,,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,_:264:_:SER,HBOND:MC_MC,_:272:_:ALA,3.419,155.078,O,N,_:272:_:ALA,,,,1,,0,0,0
492,_:266:_:ARG,HBOND:MC_MC,_:270:_:VAL,2.794,154.346,N,O,_:266:_:ARG,,,,1,,0,0,0
493,_:266:_:ARG,VDW:SC_MC,_:270:_:VAL,2.922,0,HN,C,,,,,1,,0,0,0
494,_:267:_:GLY,HBOND:MC_MC,_:270:_:VAL,3.483,171.967,O,N,_:270:_:VAL,,,,1,,0,0,0
495,_:267:_:GLY,VDW:SC_MC,_:270:_:VAL,2.723,0,HN,O,,,,,1,,0,0,0

In [33]:
# I need to make it so the code reads through all of the datafiles and then it will make its own individual csv to be interpreted.
# Store the CSV inside the folder too, once ive done that i will be able to make the program work
#  - To do now
# Once ive done this i will be looking at encoding in a gnn and making the information suitable, I also want to look into the data the different interactions.

# Now we have the Donor column, how does that effect the system, 
# Positive
# Cation
# Orientation.

Caching the list of root modules, please wait!
(This will only be done once - type '%rehashx' to reset cache!)

In [34]:
from pathlib import Path
import pandas as pd

base_dir = Path(r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset")

for path in base_dir.rglob("*.rout"): #This is reading all the folders inside of the loop 
    print(f"Reading {path}")

    with open(path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines() # this is reading the lines of the file with rout 

    headers = lines[6].rstrip("\n").split("\t") # This code is to split the data into the correct columns, with teh headers

    rows = []
    for line in lines[7:]:
        line = line.rstrip("\n")
        if not line.strip():
            continue

        parts = line.split("\t")

        if len(parts) < len(headers):
            parts += [""] * (len(headers) - len(parts))
        elif len(parts) > len(headers):
            parts = parts[:len(headers)]

        rows.append(parts)

    df = pd.DataFrame(rows, columns=headers) # Makes a dataframe

    # Save next to the .rout file
    csv_path = path.with_suffix(".csv") # Saves it to the path name with the file
    df.to_csv(csv_path, index=False)

    print(f"Saved {csv_path}") #Prints the name to double check it works.

Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\16pk_A\16pk_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\16pk_A\16pk_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1a62_A\1a62_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1a62_A\1a62_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ab1_A\1ab1_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ab1_A\1ab1_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1af7_A\1af7_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1af7_A\1af7_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ah7_A\1ah7_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ah7_A\1ah7_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ail_A\1ail_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ail_A\1ail_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1aol_A\1aol_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1aol_A\1aol_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b0n_A\1b0n_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b0n_A\1b0n_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b25_D\1b25_D.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b25_D\1b25_D.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_E\1b2s_E.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_E\1b2s_E.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_F\1b2s_F.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_F\1b2s_F.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b8d_K\1b8d_K.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b8d_K\1b8d_K.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bgf_A\1bgf_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bgf_A\1bgf_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bkp_A\1bkp_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bkp_A\1bkp_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bq8_A\1bq8_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bq8_A\1bq8_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1btk_A\1btk_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1btk_A\1btk_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bx7_A\1bx7_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bx7_A\1bx7_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_A\1bxy_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_A\1bxy_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_B\1bxy_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_B\1bxy_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1by2_A\1by2_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1by2_A\1by2_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c1k_A\1c1k_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c1k_A\1c1k_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c52_A\1c52_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c52_A\1c52_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c96_A\1c96_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c96_A\1c96_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1chd_A\1chd_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1chd_A\1chd_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cm3_A\1cm3_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cm3_A\1cm3_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1coj_A\1coj_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1coj_A\1coj_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cpq_A\1cpq_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cpq_A\1cpq_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ctf_A\1ctf_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ctf_A\1ctf_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cuo_A\1cuo_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cuo_A\1cuo_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cvr_A\1cvr_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cvr_A\1cvr_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d2t_A\1d2t_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d2t_A\1d2t_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_A\1d3y_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_A\1d3y_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_B\1d3y_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_B\1d3y_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d4t_A\1d4t_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d4t_A\1d4t_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dci_C\1dci_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dci_C\1dci_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_A\1dd3_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_A\1dd3_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_B\1dd3_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_B\1dd3_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dfu_P\1dfu_P.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dfu_P\1dfu_P.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dj0_B\1dj0_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dj0_B\1dj0_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dk8_A\1dk8_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dk8_A\1dk8_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dlj_A\1dlj_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dlj_A\1dlj_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1doi_A\1doi_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1doi_A\1doi_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dow_A\1dow_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dow_A\1dow_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dpt_A\1dpt_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dpt_A\1dpt_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dtd_B\1dtd_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dtd_B\1dtd_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dvo_A\1dvo_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dvo_A\1dvo_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dwk_A\1dwk_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dwk_A\1dwk_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dzf_A\1dzf_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dzf_A\1dzf_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e6y_D\1e6y_D.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e6y_D\1e6y_D.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e7l_B\1e7l_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e7l_B\1e7l_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ear_A\1ear_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ear_A\1ear_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1eb0_A\1eb0_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1eb0_A\1eb0_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_C\1ef1_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_C\1ef1_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_D\1ef1_D.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_D\1ef1_D.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_B\1egw_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_B\1egw_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_C\1egw_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_C\1egw_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1enj_A\1enj_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1enj_A\1enj_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1esw_A\1esw_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1esw_A\1esw_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ewf_A\1ewf_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ewf_A\1ewf_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ez3_B\1ez3_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ez3_B\1ez3_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f20_A\1f20_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f20_A\1f20_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_E\1f3u_E.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_E\1f3u_E.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_G\1f3u_G.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_G\1f3u_G.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f5n_A\1f5n_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f5n_A\1f5n_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f9p_A\1f9p_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f9p_A\1f9p_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fcz_A\1fcz_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fcz_A\1fcz_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fd3_A\1fd3_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fd3_A\1fd3_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1feh_A\1feh_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1feh_A\1feh_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fk5_A\1fk5_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fk5_A\1fk5_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fm4_A\1fm4_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fm4_A\1fm4_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_A\1fn9_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_A\1fn9_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_B\1fn9_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_B\1fn9_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fqi_A\1fqi_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fqi_A\1fqi_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_A\1fs1_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_A\1fs1_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_C\1fs1_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_C\1fs1_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fx4_A\1fx4_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fx4_A\1fx4_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fxo_G\1fxo_G.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fxo_G\1fxo_G.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g2r_A\1g2r_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g2r_A\1g2r_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_A\1g38_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_A\1g38_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_D\1g38_D.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_D\1g38_D.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g6g_A\1g6g_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g6g_A\1g6g_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7s_A\1g7s_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7s_A\1g7s_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7t_A\1g7t_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7t_A\1g7t_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g81_A\1g81_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g81_A\1g81_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g9g_A\1g9g_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g9g_A\1g9g_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gnt_A\1gnt_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gnt_A\1gnt_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gpj_A\1gpj_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gpj_A\1gpj_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqe_A\1gqe_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqe_A\1gqe_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqv_A\1gqv_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqv_A\1gqv_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gte_D\1gte_D.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gte_D\1gte_D.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gwe_A\1gwe_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gwe_A\1gwe_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h02_B\1h02_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h02_B\1h02_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h16_A\1h16_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h16_A\1h16_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h17_A\1h17_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h17_A\1h17_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h2e_A\1h2e_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h2e_A\1h2e_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h8e_G\1h8e_G.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h8e_G\1h8e_G.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h99_A\1h99_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h99_A\1h99_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hbn_E\1hbn_E.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hbn_E\1hbn_E.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hc9_B\1hc9_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hc9_B\1hc9_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hoe_A\1hoe_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hoe_A\1hoe_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hp1_A\1hp1_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hp1_A\1hp1_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hq0_A\1hq0_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hq0_A\1hq0_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1huf_A\1huf_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1huf_A\1huf_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hw1_B\1hw1_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hw1_B\1hw1_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hye_A\1hye_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hye_A\1hye_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i0v_A\1i0v_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i0v_A\1i0v_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i2t_A\1i2t_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i2t_A\1i2t_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i4m_A\1i4m_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i4m_A\1i4m_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ifg_A\1ifg_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ifg_A\1ifg_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig0_B\1ig0_B.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig0_B\1ig0_B.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig3_A\1ig3_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig3_A\1ig3_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijt_A\1ijt_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijt_A\1ijt_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijx_C\1ijx_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijx_C\1ijx_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikp_A\1ikp_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikp_A\1ikp_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikt_A\1ikt_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikt_A\1ikt_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1im5_A\1im5_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1im5_A\1im5_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1io1_A\1io1_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1io1_A\1io1_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iom_A\1iom_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iom_A\1iom_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iqq_A\1iqq_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iqq_A\1iqq_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iuq_A\1iuq_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iuq_A\1iuq_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ix9_A\1ix9_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ix9_A\1ix9_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j09_A\1j09_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j09_A\1j09_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j0p_A\1j0p_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j0p_A\1j0p_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j2l_A\1j2l_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j2l_A\1j2l_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j5u_A\1j5u_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j5u_A\1j5u_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j77_A\1j77_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j77_A\1j77_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8e_A\1j8e_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8e_A\1j8e_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8r_A\1j8r_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8r_A\1j8r_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jhs_A\1jhs_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jhs_A\1jhs_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jif_A\1jif_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jif_A\1jif_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jke_C\1jke_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jke_C\1jke_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jmx_G\1jmx_G.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jmx_G\1jmx_G.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jnr_C\1jnr_C.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jnr_C\1jnr_C.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jo0_A\1jo0_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jo0_A\1jo0_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jq5_A\1jq5_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jq5_A\1jq5_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1juv_A\1juv_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1juv_A\1juv_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jwq_A\1jwq_A.rout
Saved C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jwq_A\1jwq_A.csv
Reading C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_B\1jyo_B.rout

KeyboardInterrupt:

In [ ]:
test = pd.read_csv(r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1a62_A\1a62_A.csv")

In [ ]:
test

,NodeId1,Interaction,NodeId2,Distance,Angle,Atom1,Atom2,Donor,Positive,Cation,Orientation,Model
0,_:1:_:MET,VDW:MC_SC,_:50:_:PHE,2.706,NaN,O,H,NaN,NaN,NaN,NaN,1
1,_:2:_:ASN,HBOND:SC_MC,_:5:_:GLU,2.822,151.484,OD1,N,_:5:_:GLU,NaN,NaN,NaN,1
2,_:2:_:ASN,VDW:SC_SC,_:5:_:GLU,2.924,NaN,2HD2,CB,NaN,NaN,NaN,NaN,1
3,_:2:_:ASN,HBOND:MC_MC,_:6:_:LEU,3.409,155.940,O,N,_:6:_:LEU,NaN,NaN,NaN,1
4,_:2:_:ASN,VDW:SC_SC,_:50:_:PHE,2.377,NaN,HB2,HB1,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
337,_:127:_:ALA,_,127,ALA,RES,,0,0.000,47.260,55.870,33.160,1a62_A.pdb#127._
338,_:128:_:ARG,_,128,ARG,RES,,0,0.000,50.240,57.320,31.170,1a62_A.pdb#128._
339,_:129:_:ASN,_,129,ASN,RES,,0,0.000,52.340,60.520,31.140,1a62_A.pdb#129._
340,_:130:_:LYS,_,130,LYS,RES,,0,0.000,50.450,63.760,30.580,1a62_A.pdb#130._
341,RING finished successfully,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# I need to do this again but i need to make sure that i can seperate the tables, starting from their and make a seperate df, just containing the pdb data, so split

# The line starting with this row we will make a seperate column with the pdb/row

In [ ]:
# I want to read the column to see where it changes

In [35]:
from io import StringIO
root_dir = Path(r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset")

header1 = "NodeId1\tInteraction\tNodeId2\tDistance\tAngle\tAtom1\tAtom2\tDonor\tPositive\tCation\tOrientation\tModel"
header2 = "NodeId\tChain\tPosition\tResidue\tType\tDssp\tDegree\tBfactor_CA\tx\ty\tz\tpdbFileName\tModel"

for rout_file in root_dir.rglob("*.rout"):

    protein_name = rout_file.parent.name
    folder = rout_file.parent  # save into same folder

    try:
        with open(rout_file, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.readlines()

        idx1 = next(i for i, line in enumerate(lines) if line.strip() == header1)
        idx2 = next(i for i, line in enumerate(lines) if line.strip() == header2)

        table1_text = "".join(lines[idx1:idx2])
        table2_text = "".join(lines[idx2:])

        df1 = pd.read_csv(StringIO(table1_text), sep="\t")
        df2 = pd.read_csv(StringIO(table2_text), sep="\t")

        # save inside same folder as .rout file
        df1.to_csv(folder / f"table1_{protein_name}.csv", index=False)
        df2.to_csv(folder / f"table2_{protein_name}.csv", index=False)

        print(f"Saved CSVs in {folder}")

    except Exception as e:
        print(f"Failed on {rout_file}: {e}")

Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\16pk_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1a62_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ab1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1af7_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ah7_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ail_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1aol_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b0n_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b25_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b2s_F
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1b8d_K
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bgf_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bkp_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bq8_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1btk_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bx7_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1bxy_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1by2_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c1k_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c52_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1c96_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1chd_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cm3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1coj_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cpq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ctf_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cuo_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1cvr_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d2t_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d3y_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1d4t_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dci_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dd3_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dfu_P
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dj0_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dk8_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dlj_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1doi_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dow_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dpt_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dtd_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dvo_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dwk_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1dzf_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e6y_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1e7l_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ear_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1eb0_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ef1_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1egw_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1enj_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1esw_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ewf_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ez3_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f20_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f3u_G
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f5n_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1f9p_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fcz_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fd3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1feh_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fk5_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fm4_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fn9_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fqi_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fs1_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fx4_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1fxo_G
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g2r_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g38_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g6g_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7s_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g7t_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g81_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1g9g_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gnt_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gpj_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqe_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gqv_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gte_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1gwe_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h02_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h16_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h17_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h2e_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h8e_G
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1h99_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hbn_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hc9_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hoe_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hp1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hq0_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1huf_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hw1_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1hye_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i0v_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i2t_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1i4m_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ifg_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig0_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ig3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijt_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ijx_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikp_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ikt_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1im5_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1io1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iom_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iqq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1iuq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ix9_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j09_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j0p_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j2l_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j5u_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j77_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8e_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1j8r_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jhs_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jif_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jke_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jmx_G
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jnr_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jo0_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jq5_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1juv_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jwq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1jyo_F
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k30_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k5n_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k7c_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k7j_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1k8k_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ka1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kew_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kgq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1knt_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1koe_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kop_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kp3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1kpt_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1krn_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l2p_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l2w_I
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l2w_J
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l5o_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1l9l_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lc3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lfp_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lj5_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1llf_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lln_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lr0_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lri_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ls1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lsl_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lwb_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1lwd_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m15_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m5q_I
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m5q_Z
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m7v_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m8s_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1m9z_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1md6_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mix_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mjf_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mk0_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mlw_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1msc_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1msk_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1mv8_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n2m_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n7z_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n7z_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n8o_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n8u_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1n8v_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nf8_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ng6_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nh2_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nij_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1njh_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nkp_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nl1_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nnh_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nns_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ntv_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1nty_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o0s_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o1x_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o4k_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o75_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1o98_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1oao_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ocy_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1oh9_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ois_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ojh_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ojh_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ojq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ok0_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ouw_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1p27_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1p5g_X
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pby_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pcf_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pch_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pdo_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pp0_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ptq_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1puc_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1pv5_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q0q_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q2h_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q74_C
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q7e_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1q8f_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qau_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qb7_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qcs_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qdd_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qgi_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qhv_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ql0_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qlm_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qnx_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qw2_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qwz_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qxo_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qxo_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qxy_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1qz4_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r0k_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r5l_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r6l_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r6w_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r8m_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1r9f_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rgz_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rk8_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rl6_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rlk_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rm6_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rpo_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rqj_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rrm_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1rss_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ru4_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ryl_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1s2o_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1s9r_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1s9u_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sdi_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sei_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sei_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sf9_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1skz_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1ssq_D
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1svb_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sx3_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1sx3_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t61_E
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t7v_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t8h_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t8k_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t95_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1t9i_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tag_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tdz_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tez_B
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tg7_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tgr_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1thm_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tov_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tt8_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tuk_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tzv_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1tzw_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u07_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u09_A
Saved CSVs in C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1u55_A

In [36]:
df_test = pd.read_csv(r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset\1a62_A\table1_1a62_A.csv")

In [54]:
df_test2 = pd.read_csv(r"C:\Users\carlo\Downloads\AI\AI\dataset\dataset\6zdt_B\table2_6zdt_B.csv")

In [55]:
df_test2.columns

Index(['NodeId', 'Chain', 'Position', 'Residue', 'Type', 'Dssp', 'Degree',
       'Bfactor_CA', 'x', 'y', 'z', 'pdbFileName', 'Model'],
      dtype='object')

In [ ]:
df_test2['Dssp'].unique()

array([' ', 'E', 'T', 'G', 'H', 'S', 'B', nan], dtype=object)

In [ ]:
# How to calculate the DSSP